name: 'Install Cache'

description: 'Read / write install cache'

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
      id: cache-dependencies
      with:
        path: |
          node_modules
        key: dependencies-${{ hashFiles('package-lock.json') }}
