process.env.NEXT_PUBLIC_BASE_URL = 'fake-frontend.gov.uk'
process.env.NEXT_PUBLIC_API_URL = 'fake-backend.gov.uk'
process.env.API_KEY = 'fake-api-key'
process.env.API_PATH_CMS = '/api/pages'
process.env.NEXT_PUBLIC_API_PATH_CHART = '/charts'
process.env.API_PATH_STATS = '/stats'
process.env.NEXT_PUBLIC_USE_CHART_MOCKS = 'enabled'
