process.env.NEXT_PUBLIC_API_URL = 'http://backend.com'
process.env.API_KEY = 'fake-api-key'
process.env.API_PATH_CMS = '/api/pages'
process.env.NEXT_PUBLIC_API_PATH_CHART = '/charts'
process.env.API_PATH_STATS = '/stats'
