process.env.API_URL = 'http://fake-backend.gov.uk'
process.env.API_KEY = 'fake-api-key'
process.env.PUBLIC_API_URL = '/public-api'
process.env.GOOGLE_TAG_MANAGER_ID = 'GTM-123'
process.env.UNLEASH_SERVER_API_URL = 'http://fakedfeatureflag.gov.uk'
process.env.UNLEASH_SERVER_API_TOKEN = '123'
