name: 'Setup Node.js'

description: 'Setup Node.js'

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'
        cache: 'npm'
