version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "build"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: "build"
    schedule:
      interval: "weekly"
