/**
 * Removes specific accessibility attributes from the canvas element generated by the VectorBasemapLayer plugin.
 * These attributes, managed by our <Map /> component, may cause conflicts if left unhandled.
 * @returns {void}
 */
import { useEffect } from 'react'
import { useMap } from 'react-leaflet'

export const useBaseLayerEsri = () => {
  const map = useMap()

  return useEffect(() => {
    const container = map.getContainer()
    const vectorCanvasLayer = container.querySelector('canvas[role=region]')
    if (vectorCanvasLayer) {
      vectorCanvasLayer.removeAttribute('role')
      vectorCanvasLayer.removeAttribute('aria-label')
      vectorCanvasLayer.removeAttribute('tabindex')
    }
  }, [map])
}
