name: "Trigger deployment workflows"

description: "Triggers deployments to the Well-Known Environments"

inputs:
  token:
    description: "The required Github Personal Access Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger deployment workflow
      run: |
          curl -L -X POST https://api.github.com/repos/UKHSA-Internal/data-dashboard-infra/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"event_type":"trigger-deployments","client_payload":{"unit":false,"integration":true,"repository":"UKHSA-data-dashboard/frontend"}}'
      shell: bash
