name: 'Build cache'

description: 'Read / write build cache'

runs:
  using: 'composite'
  steps:
    - name: Cache builds
      uses: actions/cache@v3
      id: build-cache
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/out
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
