name: 'Run Cypress tests'

description: 'Run Cypress tests'

inputs:
  record-key:
    required: true
  github-token:
    required: true
  cache-folder:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Cypress tests
      uses: cypress-io/github-action@v5
      with:
        record: true
        parallel: true
        install: false
        quiet: true
        command: npm run test:e2e:ci
      env:
        CYPRESS_RECORD_KEY: ${{ inputs.record-key }}
        CYPRESS_CACHE_FOLDER: ${{ inputs.cache-folder }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
