name: Upload Scan Reports to DefectDojo
on:
  push:
    branches:
      - suyash-kumar2-patch-1

jobs:
  upload-reports:
    runs-on: ubuntu-latest
    steps:
    - name: Clone code repository
      uses: actions/checkout@v2
    
    - name: Publish report
      id: import-scan
      uses: ivanamat/defectdojo-import-scan@v1
      with:
        token: 8a5949ed4351bae231680ab5193e80de0aa3babb
        defectdojo_url: https://ec2-3-10-56-49.eu-west-2.compute.amazonaws.com
        file: zap_scan/report_json.json
        scan_type: ZAP Scan
        engagement: 1
      
    - name: Show response
      run: |
       set -e
       printf '%s\n' '${{ steps.import-scan.outputs.response }}' 
