name: Upload Scan Reports to DefectDojo
on:
  push:
    branches:
      - suyash-kumar2-patch-1

jobs:
  upload-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install required dependencies
        run: |
          pip install defectdojo_api
          pip install requests

      - name: Upload OWASP ZAP Scan Report
        run: |
          python upload_scan_report.py --scanner owasp_zap --report-path /path/to/zap_report.xml

      - name: Upload Checkov Scan Report
        run: |
          python upload_scan_report.py --scanner checkov --report-path /path/to/checkov_report.json

      - name: Upload Dependabot Scan Report
        run: |
          python upload_scan_report.py --scanner dependabot --report-path /path/to/dependabot_report.json

      - name: Upload SonarCloud Scan Report
        run: |
          python upload_scan_report.py --scanner sonarcloud --report-path /path/to/sonarcloud_report.xml

      - name: Set up DefectDojo credentials
        env:
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_URL: https://ec2-3-10-56-49.eu-west-2.compute.amazonaws.com/dashboard
        run: |
          echo "DEFECTDOJO_API_KEY=${DEFECTDOJO_API_KEY}" >> $GITHUB_ENV
          echo "DEFECTDOJO_URL=${DEFECTDOJO_URL}" >> $GITHUB_ENV

      - name: Upload reports to DefectDojo
        run: |
          python upload_reports.py
