name: Import OWASP ZAP Scan Report

on:
  push:
    branches:
      - suyash-kumar2-patch-1

jobs:
  import_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Import Scan
      uses: ivanamat/defectdojo-import-scan@v1
      with:
        defectdojo_url: 'https://ec2-3-10-56-49.eu-west-2.compute.amazonaws.com'
        token: '8a5949ed4351bae231680ab5193e80de0aa3babb'
        scan_type: 'ZAP Scan'
        file: 'zap_scan'
