name: Pipeline

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

env:
  AWS_REGION: 'eu-west-2'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for the actions/checkout

jobs:
  ###############################################################################
  # Install dependencies & build packages
  ###############################################################################

  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm ci --no-audit --no-fund

  build:
    name: Build
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: NODE_ENV=test npm run build

  ##############################################################################
  # TypeScript
  ##############################################################################

  typescript:
    name: TypeScript
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-cache
      - uses: ./.github/actions/build-cache
      - name: TypeScript Compilation
        run: npm run tsc

  ##############################################################################
  # Playwright tests - Public - (fully mocked backend)
  ##############################################################################

  e2e-tests-public:
    name: Playwright (Public) (${{ matrix.shard }}/${{ strategy.job-total }})
    needs: [build]
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-cache
      - uses: ./.github/actions/build-cache

      - name: Setup Playwright
        run: npx playwright install --with-deps

      - name: Start mock server
        id: start-mock-server
        run: |
          npm run dev:mock-server &
          echo "mockServerPID=$!" >> "$GITHUB_OUTPUT"

      - name: Wait for Mock Server
        shell: sh
        run: ./.github/scripts/wait-for-service.sh http://localhost:3005

      - name: Start Dev Server
        id: start-dev-server
        run: |
          npm run start &
          echo "devServerPID=$!" >> "$GITHUB_OUTPUT"
        env:
          NODE_ENV: test

      - name: Wait for Dev Server
        shell: sh
        run: ./.github/scripts/wait-for-service.sh http://localhost:3000

      - name: Run Playwright tests
        run: npx playwright test --grep-invert @smoke --shard=${{ matrix.shard }}/${{ strategy.job-total }}
        env:
          baseURL: http://localhost:3000

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.shard }}_${{ strategy.job-total }}
          path: playwright-report/
          retention-days: 10

      - name: Cleanup servers
        if: always()
        run: |
          kill -9 ${{ steps.start-mock-server.outputs.mockServerPID }} || true
          kill -9 ${{ steps.start-dev-server.outputs.devServerPID }} || true

