name: IaC Checkov Scan

on:
  push:
    branches:
      - suyash-kumar2-patch-1

jobs:
  scan_iac:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: suyash-kumar2-patch-1

      - name: Pull Docker Image
        run: docker pull bridgecrew/checkov
        
      - name: Run Checkov Scan
        run: |
         #echo $(ls -l bridgecrew/checkov)
         #docker run --
         docker run --volume /home/runner/work/winter-pressures-frontend/winter-pressures-frontend:/tf/:rw bridgecrew/checkov --directory /tf --soft-fail --output json --output-file-path checkov_report.json
         echo ${{ github.workspace }}
         echo $(ls -a ${{ github.workspace }}/ | grep "checkov")
         # echo $(find /home/runner/work/ -iname 'checkov_report.json')
          # 28/6/23 - ''docker run --rm --volume ${{ github.workspace }}:/tf bridgecrew/checkov'' is running checkov in a container, ''output'' is saving file
          # in the same container; just need to figure out where it is - a filepath issue! Then we can figure out a way to upload that
          
      - name: Upload Checkov Report
        uses: actions/upload-artifact@v3
        with:
          name: checkov-report
          path: ${{ github.workspace }}/checkov_report.json
