name: IaC Scan

on:
  push:
    branches:
      - suyash-kumar2-patch-1

jobs:
  scan_iac:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: suyash-kumar2-patch-1

      - name: Pull Docker Image
        run: docker pull bridgecrew/checkov
        
      - name: Run Checkov Scan
        run: |
         #mkdir -p .github/workflows/artifacts
         #touch .github/workflows/artifacts/checkov_report.json
         docker run --rm --volume ${{ github.workspace }}:/tf bridgecrew/checkov --directory /tf --soft-fail --output json --output-file-path checkov_report.json
         echo $(find ${{ github.workspace }} -iname 'checkov_report.json')
          
      - name: Upload Checkov Report
        uses: actions/upload-artifact@v3
        with:
          name: checkov-report
          path: ${{ github.workspace }}/checkov_report.json
