name: "ZAP Baseline Scan"
 
on:
  push:
    branches:
      - suyash-kumar2-patch-1
 
jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest
 
    steps:
       - uses: actions/checkout@v3
         with:
           ref: suyash-kumar2-patch-1
       - name: Installing node.js
         uses: actions/setup-node@v3
         with:
          node-version: 18
       - name: install dependencies
         run: npm i
       - name: create frontend hosting script
         run: |
            touch hosting.sh
            echo "npm run dev" >> hosting.sh
            chmod u+x hosting.sh
       - name: start hosting frontend
         run: nohup ./hosting.sh &
       - name: Pulling Docker Image
         run: docker pull owasp/zap2docker-stable
       - name: create zap hosting script
         run: |
            touch zaphosting.sh
            echo "docker run -p 8080:3000 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080" >> zaphosting.sh
            chmod u+x zaphosting.sh
       - name: start hosting zap
         run: nohup ./zaphosting.sh &
         # -p 8090:8090 means that port 8090 on the host machine is mapped to port 8090 inside the container. 
         # This allows you to access the service running inside the container on port 8090 from your host machine.
       - name: OWASP ZAP
         uses: zaproxy/action-baseline@v0.7.0
         with:
           target: "http://localhost:3000"
           fail_action: false
           # OWASP scan outputs .HTML and .json format reports
           
       - name: Checkout Repository for ZAP Report to DefectDojo
         uses: actions/checkout@v2

       - name: Import Scan
         uses: ivanamat/defectdojo-import-scan@v1
         with:
           defectdojo_url: 'https://ec2-3-10-56-49.eu-west-2.compute.amazonaws.com'
           token: '8a5949ed4351bae231680ab5193e80de0aa3babb'
           scan_type: 'ZAP Scan'
           file: '${{ github.workspace }}/baseline_reports/zap_scan/report_json.json'
